# Generated by https://github.com/buildkite/cli/blob/master/.github/tap-release.yml

class Bk < Formula
  homepage "https://github.com/buildkite/cli"
  desc "A command line interface for Buildkite."
  url "https://github.com/buildkite/cli/releases/download/v0.4.1/bk-darwin-amd64-0.4.1"
  version "v0.4.1"
  sha256 "8f4e98657285ed841562cd5e34b55d21d4561d9a4edfcf7d74a3165325d844f1"

  def install
    mv "bk-darwin-amd64-0.4.1", "bk"
    bin.install "bk"
  end

  test do
    assert_match "bk #{version}", shell_output("#{bin}/bk --version 2>&1")
  end
end
