# Generated by https://github.com/buildkite/cli/blob/master/.github/tap-release.yml

class Bk < Formula
  homepage "https://github.com/buildkite/cli"
  desc "A command line interface for Buildkite."
  url "https://github.com/buildkite/cli/releases/download/v0.5.0/bk-darwin-amd64-0.5.0"
  version "v0.5.0"
  sha256 "b6e16d001bdc3bec071c1c1f385f6a51fb21d0e4e79a5827be88fa19beb13683"

  def install
    mv "bk-darwin-amd64-0.5.0", "bk"
    bin.install "bk"
  end

  test do
    assert_match "bk #{version}", shell_output("#{bin}/bk --version 2>&1")
  end
end
